# Generated by Django 3.1.7 on 2021-03-22 05:27

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import survey.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, validators=[survey.models.validate_url_name])),
                ('redirect_url', models.CharField(default='#', max_length=250)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SurveySession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyheader')),
            ],
        ),
        migrations.CreateModel(
            name='SurveySection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head', models.BooleanField(default=False)),
                ('name', models.CharField(default='survey_description', max_length=45, validators=[survey.models.validate_url_name])),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('subheading', models.CharField(blank=True, max_length=4096, null=True)),
                ('code', models.CharField(max_length=8)),
                ('start_map_postion', django.contrib.gis.db.models.fields.PointField(default='POINT(30.317 59.945)', srid=4326)),
                ('start_map_zoom', models.IntegerField(default=12)),
                ('next_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_next_section', to='survey.surveysection')),
                ('prev_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_prev_section', to='survey.surveysection')),
                ('survey_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyheader')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=survey.models.question_code_generator, max_length=50)),
                ('order_number', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('subtext', models.CharField(blank=True, max_length=512, null=True)),
                ('input_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('choice', 'Choices'), ('multichoice', 'Multiple Choices'), ('range', 'Range'), ('rating', 'Rating'), ('datetime', 'Date/Time'), ('point', 'Geo Point'), ('line', 'Geo Line'), ('polygon', 'Geo Polygon'), ('image', 'Image'), ('text_line', 'Line'), ('html', 'HTML')], max_length=80)),
                ('required', models.BooleanField(default=False)),
                ('color', models.CharField(default='#000000', help_text='HEX color, as #RRGGBB', max_length=7, verbose_name='Color')),
                ('icon_class', models.CharField(blank=True, default='', help_text='Must be Font-Awesome class', max_length=80, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('option_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.optiongroup')),
                ('parent_question_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('survey_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveysection')),
            ],
        ),
        migrations.CreateModel(
            name='OptionChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.IntegerField()),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.optiongroup')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric', models.FloatField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('yn', models.BooleanField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('line', django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('choice', models.ManyToManyField(to='survey.OptionChoice')),
                ('parent_answer_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('survey_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveysession')),
            ],
        ),
    ]
