# Generated by Django 4.2.27 on 2026-01-31 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.optiongroup'),
        ),
        migrations.AlterField(
            model_name='surveyheader',
            name='redirect_url',
            field=models.CharField(default='#', help_text='URL to redirect after survey completion. E.g.: /thanks/ or https://example.com', max_length=250),
        ),
    ]
