# Generated by Django 4.2.27 on 2026-02-03 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_option_group_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyheader',
            name='available_languages',
            field=models.JSONField(blank=True, default=list, help_text='List of ISO 639-1 language codes, e.g. ["en", "ru", "de"]'),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='language',
            field=models.CharField(blank=True, help_text='Selected language code (ISO 639-1)', max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='SurveySectionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='ISO 639-1 language code', max_length=10)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('subheading', models.CharField(blank=True, max_length=4096, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='survey.surveysection')),
            ],
            options={
                'unique_together': {('section', 'language')},
            },
        ),
        migrations.CreateModel(
            name='QuestionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='ISO 639-1 language code', max_length=10)),
                ('name', models.CharField(blank=True, max_length=512, null=True)),
                ('subtext', models.CharField(blank=True, max_length=512, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='survey.question')),
            ],
            options={
                'unique_together': {('question', 'language')},
            },
        ),
        migrations.CreateModel(
            name='OptionChoiceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='ISO 639-1 language code', max_length=10)),
                ('name', models.CharField(max_length=256)),
                ('option_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='survey.optionchoice')),
            ],
            options={
                'unique_together': {('option_choice', 'language')},
            },
        ),
    ]
