# Generated by Django 4.2.27 on 2026-02-09 05:05

from django.db import migrations, models
import survey.models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_add_multilang_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selected_choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.JSONField(blank=True, null=True, validators=[survey.models.ChoicesValidator()]),
        ),
    ]
