# Generated by Django 4.2.27 on 2026-02-09 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_migrate_choices_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='optionchoicetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='optionchoicetranslation',
            name='option_choice',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option_group',
        ),
        migrations.DeleteModel(
            name='OptionChoice',
        ),
        migrations.DeleteModel(
            name='OptionChoiceTranslation',
        ),
        migrations.DeleteModel(
            name='OptionGroup',
        ),
    ]
