# Generated by Django 4.2.27 on 2026-02-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_remove_legacy_option_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyheader',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Marks completed surveys whose results can be shown'),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('demo', 'Demo'), ('public', 'Public')], default='private', help_text='Controls whether survey appears on the landing page', max_length=10),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
                ('body', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='stories/')),
                ('story_type', models.CharField(choices=[('map', 'Map'), ('open-data', 'Open Data'), ('results', 'Results'), ('article', 'Article')], default='article', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('survey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='survey.surveyheader')),
            ],
            options={
                'verbose_name_plural': 'stories',
            },
        ),
    ]
