# Generated by Django 4.2.27 on 2026-02-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_landing_page_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyheader',
            name='thanks_html',
            field=models.JSONField(blank=True, default=dict, help_text='Custom HTML for thanks page. Dict keyed by language: {"en": "<h1>Thanks!</h1>", "ru": "<h1>Спасибо!</h1>"} or a plain string.'),
        ),
    ]
