# Generated by Django 4.2.27 on 2026-02-16 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_finalize_test_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyheader',
            name='canonical_survey',
            field=models.ForeignKey(blank=True, help_text='For archived versions, points to the canonical survey', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='survey.surveyheader'),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='is_canonical',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='published_version',
            field=models.ForeignKey(blank=True, help_text='For draft copies, points to the canonical survey being edited', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_copies', to='survey.surveyheader'),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='surveysession',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='survey.surveyheader'),
        ),
        migrations.AddIndex(
            model_name='surveyheader',
            index=models.Index(fields=['canonical_survey', '-version_number'], name='survey_surv_canonic_ffc037_idx'),
        ),
    ]
