# Generated by Django 4.2.27 on 2026-04-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_versioning_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysection',
            name='use_geolocation',
            field=models.BooleanField(default=False),
        ),
    ]
