# Generated by Django 4.2.27 on 2026-04-01 14:13

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0019_surveysection_use_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysection',
            name='start_map_postion',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(13.405 52.52)', srid=4326),
        ),
    ]
