# Generated by Django 4.2.27 on 2026-04-03 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_default_map_position_berlin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('session_start', 'Session Start'), ('section_view', 'Section View'), ('section_submit', 'Section Submit'), ('survey_complete', 'Survey Complete'), ('page_load', 'Page Load')], db_index=True, max_length=30)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='survey.surveysession')),
            ],
            options={
                'indexes': [models.Index(fields=['session', 'event_type'], name='survey_surv_session_67af8f_idx'), models.Index(fields=['session', 'created_at'], name='survey_surv_session_b3d9f3_idx')],
            },
        ),
    ]
