# Generated by Django 4.2.27 on 2026-04-03 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0021_add_survey_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyevent',
            name='event_type',
            field=models.CharField(choices=[('session_start', 'Session Start'), ('section_view', 'Section View'), ('section_submit', 'Section Submit'), ('survey_complete', 'Survey Complete'), ('page_load', 'Page Load'), ('page_leave', 'Page Leave')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='TrackedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_links', to='survey.surveyheader')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
