# Generated by Django 4.2.27 on 2026-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_add_tracked_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyheader',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
