# Generated by Django 4.2.27 on 2026-04-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0023_add_cover_image_and_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='validation_status',
            field=models.CharField(blank=True, choices=[('', 'No status'), ('approved', 'Approved'), ('not_approved', 'Not approved'), ('on_hold', 'On hold')], db_index=True, default='', max_length=15),
        ),
    ]
