# Generated by Django 4.2.27 on 2026-04-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_session_validation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='surveysession',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
