# Generated by Django 4.2.27 on 2026-04-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_session_tags_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='validation_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Per-question validation: {min_value, max_value, outlier_sigma, min_length, area_outlier_factor}'),
        ),
        migrations.AddField(
            model_name='surveyheader',
            name='validation_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Survey-level validation thresholds: {fast_threshold_seconds, duplicate_window_hours}'),
        ),
    ]
